version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:z
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    networks:
      - observability

  # blackbox-exporter:
  #   image: prom/blackbox-exporter:latest
  #   container_name: blackbox-exporter
  #   ports:
  #     - "9115:9115"
  #   volumes:
  #     - ./blackbox-exporter.yaml:/etc/blackbox_exporter/config.yaml:z
  #   command:
  #     - "--config.file=/etc/blackbox_exporter/config.yaml"
  #   depends_on:
  #     - prometheus
  #   networks:
  #     - observability

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100" # Loki HTTP endpoint
    volumes:
      - loki-data:/tmp/loki
      - ./loki.yaml:/etc/loki/loki.yaml:z
    command: -config.file=/etc/loki/loki.yaml
    depends_on:
      - prometheus
    networks:
      - observability

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - "3200:3200"   # Tempo query endpoint
      - "9095:9095"   # Tempo gRPC endpoint
      - "4317:4317"   # OpenTelemetry gRPC endpoint
      - "4318:4318"   # OpenTelemetry HTTP endpoint
    volumes:
      - tempo-data:/var/lib/tempo
      - ./tempo.yaml:/etc/tempo/tempo.yaml:z
    command: ["-config.file=/etc/tempo/tempo.yaml"]
    environment:
      - TEMPO_STORAGE_BACKEND=local
    depends_on:
      - loki
    networks:
      - observability

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - "12345:12345" # Alloy HTTP endpoint
    volumes:
      - alloy-data:/var/lib/alloy
      - ./config.alloy:/etc/alloy/config.alloy:z
    depends_on:
      - loki
      - tempo
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor metricsSummary
      - GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-exploretraces-app/grafana-exploretraces-app-latest.zip;grafana-traces-app;grafana-clock-panel,grafana-piechart-panel
      #- GF_SECURITY_ADMIN_USER=admin
      #- GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:z
    depends_on:
      - prometheus
      - loki
      - tempo
    networks:
      - observability

  api-backend:
    build:
      context: ../api-backend
      dockerfile: Dockerfile
    container_name: api-backend
    command: ["node", "dist/index.js"]
    ports:
      - "8000:8000"  # API backend HTTP endpoint
      - "9464:9464"  # Prometheus metrics endpoint
    environment:
      - PORT=8000
      - LOG_LEVEL=trace
      #- LOKI_HOST=http://loki:3100
      - OTEL_DEBUG=1
      #- OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://tempo:4318/v1/traces
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://tempo:4317
      - OTEL_EXPORTER_OTLP_LOGS_ENDPOINT=http://alloy:4317
      #- OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_EXPORTER_OTLP_TRACES_INSECURE=true
      - OTEL_EXPORTER_OTLP_METRICS_INSECURE=true
      - OTEL_EXPORTER_OTLP_LOGS_INSECURE=true
      #- OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_METRICS_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_LOGS_PROTOCOL=grpc
    depends_on:
      - tempo
      - alloy
    networks:
      - observability

volumes:
  prometheus-data:
  tempo-data:
  alloy-data:
  loki-data:
  grafana-data:

networks:
  observability:
